### ISSUE TITLE
D8 sets boot loader into programming mode

### ISSUE THREAD

**Issue by hinnerkweiler** [AK-Homberger/NMEA0183-WiFi-Multiplexer#1]
Hi, 

I just finished reconstructing this. However, after some testing I only get it to work when I leave D8 physically disconnected. The Levelshifter seems to send HIGH as soon as the PCB receives power and causes the booting ESP to head straight into Programming mode. Console says: "waiting for host", and that's forever.

I found this for a possible reason:
```
Bootloader Modes

The bootloader can go into a number of modes depending on the state of GPIOs 0, 2 and 15. The two useful modes are the UART download mode (for flashing new firmware) and the flash startup mode (which boots from flash).
						GPIO0(D3) | GPIO2(D4) | GPIO15(D8)
UART Download Mode (Programming)			0 	1 	0
Flash Startup (Normal)					1 	1 	0
SD-Card Boot						0 	0 	1
```

Did you manage to work around this to get the 2nd port activated?

Apparently it seems not to happen using a D1-Mini-Pro (I have none at hand to verify) However on regular D1-Mini (exactly the one you liked to) others also have run into similar problems and reproduced the issue:
https://forum.fhem.de/index.php?topic=71059.0 

Hinnerk

**Comment by AK-Homberger** [comment]
Changes done.

**Comment by hinnerkweiler** [comment]
Ah, sure, that is the simple solution, it worked, while testing everything without the level shifter... Just hoped for a better solution than cutting tracks on the PCBs and run a wire... Just had three boards delivered and found the issue putting everything together. :-/

**Comment by AK-Homberger** [comment]
Hi Hinnerk,

Unfortunately, there is no better solution for the old PCBs. But cutting one wire would have been enough. Just cut D8 line and connect to D6. Then change the pin definitions in the code.

And: This is a free of charge DIY solution. This is not a cmmercial product with all testing done and warranty. And my ability to buy and test the full hardware with the PCB is limited.  But I'm happy to react on identified issues and do the corrections/improvements (as I did here).

The situation would be better if at least a few people would use the PayPal button for donations for new hard/software. 
But so far only one person used this opportunity. 

Regards,
Andreas
