### ISSUE TITLE
Wi-Fi with nmea 0183 data.

### ISSUE THREAD

**Issue by AlksSAV** [AK-Homberger/NMEA0183-WiFi-Multiplexer#2]
Great device!
I have an echo sounder that can transmit nmea data over Wi Fi. I want to transmit this data to the Ardupilot autopilot. 
Is it possible to make nmea 0183 received over Wi-Fi network mixed with the first RS232 and transmitted to the second RS232? 
Or just received nmea 0183 via Wi-Fi transmitted over RS232.

**Comment by AK-Homberger** [comment]
With the current PCB this is not directly possible. The serial lines are input only.
But with a few changes in hard and software this would be possible.

**Comment by AlksSAV** [comment]
> With the current PCB this is not directly possible. The serial lines are input only.
> 
> But with a few changes in hard and software this would be possible.

It would be great to get this opportunity. For device tests, you can do without a PCB. If possible, please do the software part.

**Comment by AK-Homberger** [comment]
Currently I don't have the time to do this. But I would suggest that you try to do this by your own. Intead of reading from Serial you have to read from a TCP connection and write the message to Serial. Information on how to use TCP is available here: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino
