### ISSUE TITLE
all nmea data is sent twice

### ISSUE THREAD

**Issue by maxnae** [AK-Homberger/NMEA0183-WiFi-Multiplexer#4]
Regardless of whether I switch off a softserial or not. all nmea data is sent twice. Can this be prevented?

**Comment by AK-Homberger** [comment]
Try to commet out the second send code and check if its now sent only once.

/*
if (GetNMEA0183Message2() == true) {    // Get NMEA sentences from serial#2
    SendNMEA0183Message(buf2);    // Send to clients
  }
*/

And check that there is no shortcut between both serial RX lines.

**Comment by maxnae** [comment]
Thanks.
I tried but unfortunately the result is the same. There is also no connection at D6 and D7.

$GPGSV,1,1,00*79
$GPGSV,1,1,00*79
$GLGSV,1,1,00*65
$GLGSV,1,1,00*65
$GNGLL,,,,,,V,N*7A
$GNGLL,,,,,,V,N*7A
$GNRMC,,V,,,,,,,,,,N*4D
$GNRMC,,V,,,,,,,,,,N*4D
$GNVTG,,,,,,,,,N*2E
$GNVTG,,,,,,,,,N*2E
$GNGGA,,,,,,0,00,99.99,,,,,,*56
$GNGGA,,,,,,0,00,99.99,,,,,,*56
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GPGSV,1,1,00*79
$GPGSV,1,1,00*79
$GLGSV,1,1,00*65
$GLGSV,1,1,00*65
$GNGLL,,,,,,V,N*7A
$GNGLL,,,,,,V,N*7A
is it maybe necessary to have a delay when reading softserial?
best regards max

**Comment by maxnae** [comment]
Here is the output

68
13
$GNRMC,,V,,,,,,,,,,N*4D
10
$GNRMC,,V,,,,,,,,,,N*4D
36
71
78
86
84
71
44
44
44
44
44
44
44
44
44
78
42
50
69
13
$GNVTG,,,,,,,,,N*2E
10
$GNVTG,,,,,,,,,N*2E
36
71
78
71
71
65
44
44
44
44
44
44
48
44
48
48
44
57
57
46
57
57
44
44
44
44
44
44
42
53
54
13
$GNGGA,,,,,,0,00,99.99,,,,,,*56
10
$GNGGA,,,,,,0,00,99.99,,,,,,*56
36
71
78
71
83
65
44
65
44
49
44
44
44
44
44
44
44
44
44
44
44
44
44
57
57
46
57
57
44
57
57
46
57
57
44
57
57
46
57
57
42
50
69
13
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
10
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
36
71
78
71
83
65
44
65
best regards max

**Comment by AK-Homberger** [comment]
Each caracter is received only once. That's OK so far. But then the buffer is sent twice. One time after CR (\n) and another time after receiving LF (\r). But that should not happen.

Please add these both lines in both receive functions:

if(ReceivedChars == 0 && (Char == '\r')) return false;
if(ReceivedChars == 0 && (Char == '\n')) return false;

before this code:

if ( (Char == '\n') || (Char == '\r') ) {
      ReceivedChars = 0;
      return true;
    }

Then it should work. It looks like my test system only sent one of the line end codes.

**Comment by maxnae** [comment]
wonderful thanks worked.

one more question, how can I filter different gps sets so that they are not sent further or specify which ones to go through?

$GNVTG
$GPGSV
$GLGSV

best regards max

**Comment by AK-Homberger** [comment]
You have to parse the NME0183 messages. You can try to use this library https://github.com/ttlappalainen/NMEA0183). But I think it's not directly working with SoftwareSerial.

**Comment by maxnae** [comment]
Thank you very much, it looks like this is working perfectly.
I modified that a bit. looks awesome

  // Receive and check message codes to suppress
  if (NMEA0183_1.GetMessage(NMEA0183Msg)) {    // Get NMEA sentences from serial#1
    
    if (!((strcmp(NMEA0183Msg.Sender(), "GP") == 0) && NMEA0183Msg.IsMessageCode("GSV") ||
          (strcmp(NMEA0183Msg.Sender(), "GN") == 0) && NMEA0183Msg.IsMessageCode("VTG") ||
          (strcmp(NMEA0183Msg.Sender(), "GN") == 0) && NMEA0183Msg.IsMessageCode("GLL") ||
          (strcmp(NMEA0183Msg.Sender(), "GL") == 0) && NMEA0183Msg.IsMessageCode("GSV"))) { 

      if (NMEA0183Msg.GetMessage(buf, MAX_NMEA0183_MESSAGE_SIZE - 1)) {
         SendNMEA0183Message(buf);    // Send to clients

best regards max

**Comment by maxnae** [comment]
another question. I'm currently trying to transmit Softserial 1 filtered and Softserial2 as RAW (is not an NMEA sentence). Unfortunately I seem to have made a mistake here. 
[NMEA083-Parser-WiFiMultiplexer_mod.txt](https://github.com/AK-Homberger/NMEA0183-WiFi-Multiplexer/files/9987979/NMEA083-Parser-WiFiMultiplexer_mod.txt)
best regards max

**Comment by maxnae** [comment]
Thank you very much
best regards max
